### ISSUE TITLE
probabilities are likely overestimated (lack of calibration)

### ISSUE THREAD

**Issue by artdgn** [DefiLlama/yield-ml#2]
Model confidence scores can't be interpreted as probabilities directly please see [sklearn docs for a good explanation](https://scikit-learn.org/stable/modules/calibration.html). For RF especially, the "naive" probas would be highly over/under estimated. This issue is even worse in this case because time split isn't used.

I assume that the site's probabilities are naive model confidences because it doesn't look like the committed notebook has a separate probability calibration part (that would also require a an additional validation data split).

Alternatives:
1. To avoid calibration, just splitting confidences into categories by confidence quantile (e.g. top 25%, middle 50%, bottom 25%).
2. If actual probabilities are needed, add the additional step of calibrating probabilities (that requires another data split, and training another minimal model on top of the confidences).

![image](https://user-images.githubusercontent.com/29574203/167234073-fcaded49-a8d5-4723-a35c-3361f94a0bab.png)

**Comment by slasher125** [comment]
thats right, not calibrated. generally afaik, even though RF predict_proba are not real probabilities, the relative frequencies in the leaf nodes should converge to probabilities if the ensemble is large enough. i recall reading a paper about that a long time ago...

Do you want to give calibration a go? check out the other issue, replied to that one as well!

**Comment by artdgn** [comment]
@slasher125 

> even though RF predict_proba are not real probabilities, the relative frequencies in the leaf nodes should converge to probabilities if the ensemble is large enough

1. *"In theory there is no difference between practice and theory..."* :) The sklearn doc page I've linked has good examples.
2. This might happen in a case for a. large enough dataset b. IID data c. interpolating. While here the data has distribution shifts between training and prediction, internally correlated, all kinds of sampling biases.

> Do you want to give calibration a go?

Low chances of me finding the time for that unfortunately. I'd recommend to switch to confidence categories in the site: low, medium, high, based on confidence quantiles, as a way to provide the users with some subjective level of confidence, but without showing most-likely incorrect probabilities.

**Comment by slasher125** [comment]
Sorry about the late reply -_-
Thanks again for the input, was very helpful and I learned something new. 
we applied that change recently :)
Closing this issue
